config/routes.rb
Sanatid::Application.routes.draw do
  class FormatTest
    attr_accessor :mime_type

    def initialize(format)
      @mime_type = Mime::Type.lookup_by_extension(format)
    end

    def matches?(request)
      request.format = :html unless request.format == Mime::Type.lookup_by_extension(:json)
      request.format == mime_type
    end
  end

  get 'robots.:format', to: 'application#robots'

  constraints subdomain: ['staff', 'devstaff'] do
    scope module: 'staff', as: 'staff' do
      root to: 'staff_application#index'

      get 'login', to: 'sessions#new', as: 'login'
      get 'logout', to: 'sessions#destroy', as: 'logout'

      resources :sessions
      resources :companies do
        resources :product_subscriptions
        resources :invoices
        get 'cancel_subscription/:id', to: 'product_subscriptions#cancel_subscription', as: 'cancel_subscription'
      end
      get 'maps/companies', to: 'companies#maps', as: 'company_map'
      resources :customers
      resources :staffs
      resources :service_fields
      resources :services
      resources :blogs
      resources :pages
      resources :staffs
      resources :submissions
      resources :newsletter_subscribers
      resources :products
      resources :emails
      resources :product_subscriptions
      resources :clips
      resources :product_families
      resources :coupons
      get 'my_leads', to: 'leads#my_leads'
      get 'leads/signups', to: 'leads#signups', as: 'leads_signups'
      post 'leads/:id/send_presentation', to: 'leads#send_presentation', as: 'lead_send_presentation'
      post 'leads/assign', to: 'leads#assign_leads', as: 'assign_leads'
      resources :leads
      resources :lead_events
      resources :reminders
      resources :uploads
    end
  end

  get 'terms/company', to: 'api/payments#terms_company'
  get 'product_subscriptions/invoice/:id', to: 'api/product_subscriptions#invoice'
  get 'sitemap.xml', to: 'api/sitemaps#index', as: 'sitemap', defaults: { format: :xml }
  get '*path', :to => 'application#index', :constraints => FormatTest.new(:html)
  get '/', :to => 'application#index', :constraints => FormatTest.new(:html)

  namespace :api do
    resources :service_fields, defaults: { format: 'json' }
    resources :services, defaults: { format: 'json' }
    resources :customers, defaults: { format: 'json' }
    resources :companies, defaults: { format: 'json' }
    get '/frontpage_promotions/:id', to: 'companies#frontpage_promotions'
    get '/flow_promotions', to: 'companies#flow_promotion'
    resources :vouchers, defaults: { format: 'json' }
    resources :clips, defaults: { format: 'json' }
    resources :newsletter_subscribers, defaults: { format: 'json' }
    resources :blogs, defaults: { format: 'json' }
    resources :pages, defaults: { format: 'json' }
    resources :staffs, defaults: { format: 'json' }
    resources :submissions, defaults: { format: 'json' }
    resources :products, defaults: { format: 'json' }
    resources :product_families, defaults: { format: 'json' }
    resources :product_subscriptions, defaults: { format: 'json' }
    resources :messages, defaults: { format: 'json' }
    resources :reviews, defaults: { format: 'json' }
    resources :commission_lines, defaults: { format: 'json' }
    resources :menu_items, defaults: { format: 'json' }
    resources :facility_images, defaults: { format: 'json' }
    resources :bookings, defaults: { format: 'json' }

    resources :payments, defaults: { format: 'json' }
    match '/payment' => 'payments#dispatch_handler', via: 'post'
    match '/payment/list_invoices/:id' => 'payments#list_invoices', via: 'get'

    # Product Subscription.
    post '/product_subscriptions/change_subscription_product/:id', to: 'product_subscriptions#change_subscription_product'
    post '/product_subscriptions/cancel_subscription/:id', to: 'product_subscriptions#cancel_subscription'
    post '/product_subscriptions/signup_subscription/:id', to: 'product_subscriptions#signup_subscription'
    post '/product_subscriptions/reactivate_subscription/:id', to: 'product_subscriptions#reactivate_subscription'

    post '/demo/init', to: 'demo#init_demo'

    resources :sessions, except: [:new, :edit, :destroy]
    post 'session' => 'sessions#create', defaults: { format: :json }
    post 'session/reset' => 'sessions#reset', defaults: { format: :json }
  end
end

app/models/company.rb
class Company < User
  include Slugifier

  has_many :vouchers
  has_many :company_pages
  has_and_belongs_to_many :services
  has_and_belongs_to_many :service_fields
  has_many :product_subscriptions
  has_many :reviews
  has_many :reservations
  belongs_to :lead
  has_many :invoices
  has_many :commission_lines
  has_many :menu_items
  has_many :calendar_events
  has_many :facility_images
  has_many :bookings

  serialize :opening_hours
  serialize :payment_methods
  mount_uploader :logo, LogoUploader

  validates :subscription_status, inclusion: { in: %w(active canceled expired passive), message: "%{value} is not a valid status" }
  validates :phone, :company_name, presence: true
  validates :email, format: { with: /\A(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})\z/i }
  validates :phone, format: { with: /\A\d{8}/ }

  before_create :create_slug, :init_payment_methods
  before_save :sanitize_description

  scope :active, -> { where(active: true) }
  scope :newest, -> { order('created_at DESC') }
  scope :active_subscription, -> { where(subscription_status: 'active') }
  scope :address_contains, ->(address) { where('address like ?', "%#{address}%") }

  def sanitize_description
    allowed_elements = Array.new Sanitize::Config::RELAXED[:elements]
    allowed_elements.delete('a')
    self.description = Sanitize::fragment(description, Sanitize::Config.merge(Sanitize::Config::RELAXED,
                                                                         elements: allowed_elements))
  end

  def fundamental_subscription
    self.product_subscriptions.active.each do |subscription|
      return subscription if subscription.product && subscription.product.fundamental
    end
    nil
  end

  def active_invoice
    invoice = self.invoices.open.where('invoices.end_date > ?', Time.now).first
    unless invoice.present?
      return init_invoice
    end
    invoice
  end

  def init_invoice
    if self.fundamental_subscription.present?
      invoice = Invoice.new company: self, state: 'open'

      previous_invoice = self.invoices.last
      if previous_invoice.present?
        # Should start the day after, the last expired.
        invoice.start_date = previous_invoice.end_date + 1.day
        invoice.end_date = previous_invoice.end_date + 31.days
      else
        invoice.start_date = fundamental_subscription.renewed_at
        invoice.end_date = 30.days.from_now.end_of_day
      end
      invoice.save
      invoice
    end
  end

  def self.find_by_frontpage_promotion(level, num)
    product_handle = "frontpage-promotion-#{level}"

    self.includes(:services).joins(product_subscriptions: [:product])
    .where(products: {handle: product_handle}, product_subscriptions: {active: true})
    .order('RANDOM()').limit(num)
  end

  def self.find_by_flow_promotion(level, num, cord)
    product_handle = "flow-promotion-#{level}"

    self.joins(product_subscriptions: [:product])
    .where(products: {handle: product_handle}, product_subscriptions: {active: true})
    .order('RANDOM()').limit(num)
    .near(cord, 15)
  end

  private

  def create_slug
    unless self.slug.present?
      self.slug = self.generate_slug(self.company_name)
    end
  end

  def init_payment_methods
    self.payment_methods = []

    I18n.t('config.company_payment_methods').each do |payment_method|
      self.payment_methods << {name: payment_method, enabled: false}
    end
  end
end

app/controllers/api/companies_controller.rb
class Api::CompaniesController < ApplicationController
  before_filter :ensure_authenticated_user, only: [:update]
  before_filter :ensure_active_token, only: [:show]
  respond_to :json

  def index
    if params[:slug].present?
      company = Company.active.where(slug: params[:slug]).presence || Lead.public.where(slug: params[:slug])

      return respond_with company
    end

    if params[:service_field].present? && params[:lat].present? && params[:lon].present?
      cords = params[:lat], params[:lon]

      companies = Company.active
        .joins(:service_fields)
        .where(service_fields: {name: 'Massage'} )
        .near(cords, 80)
        .limit(15)

      companies_arr = ActiveModel::Serializer.build_json(self, companies, cords: cords).as_json

      final_json = Hash.new
      final_json['companies'] = companies_arr['companies']

      return render json: final_json.to_json

    elsif params[:lat].present? && params[:lon].present?
      cords     = params[:lat], params[:lon]
      companies = Company.active.near(cords, 80).limit(15)

      companies_arr = ActiveModel::Serializer.build_json(self, companies, cords: cords).as_json

      final_json = Hash.new
      final_json['companies'] = companies_arr['companies']

      return render json: final_json.to_json
    end

    page_limit = params[:limit] || 20
    respond_with Company.active.newest.page(params[:page]).per(page_limit), each_serializer: BasicCompanySerializer
  end

  def show
    respond_with Company.active.find(params[:id])
  end

  # When a company wants to be created, we create a lead, which our salesmen then can contact.
  def create
    company = Company.new company_params
    # Generate a new password for the company.
    password = Digest::SHA2.hexdigest(rand(1000000).to_s)[0..8]
    company.password = company.password_confirmation = password

    if company.save
      # Send welcome mail to company, with login information.
      CompanyMailer.delay(priority: 10).welcome_company(company, password)
      respond_with :api, company
    else
      respond_with company
    end
  end

  def frontpage_promotions
    first_row = Company.find_by_frontpage_promotion(1, 4)
    second_row = Company.find_by_frontpage_promotion(2, 4)
    third_row = Company.find_by_frontpage_promotion(3, 4)
    rows = first_row + second_row + third_row
    is_clear = rows.empty?

    frontpage_promotions = {
      frontpage_promotion: {
        id: 1,
        # isEmpty is reserved in emberjs.
        is_clear: is_clear,
        first_row_ids: first_row.map(&:id),
        second_row_ids: second_row.map(&:id),
        third_row_ids: third_row.map(&:id)
      },
      companies: ActiveModel::ArraySerializer.new(rows, each_serializer: BasicCompanySerializer)
    }

    respond_with frontpage_promotions
  end

  def update
    company = Company.find(params[:id])

    if company == current_user
      company.update_attributes(company_params)
    end

    respond_with company
  end

  private

  def company_params
    params.require(:company).permit(
      :name,
      :logo,
      :email,
      :phone,
      :description,
      :password,
      :password_confirmation,
      :address,
      :company_name,
      :company_email,
      :cvr,
      payment_methods: [
        [:name, :enabled]
      ],
      opening_hours: [
        :monday,
        :tuesday,
        :wednesday,
        :thursday,
        :friday,
        :saturday,
        :sunday
      ],
      service_field_ids: []
    )
  end
end

app/controllers/api/staffs_controller.rb
class Api::StaffsController < ApplicationController
  respond_to :json

  def index
    respond_with Staff.active.published.order(:created_at).load
  end
end

app/controllers/staff/blogs_controller.rb
class Staff::BlogsController < Staff::StaffApplicationController
  def index
    @blogs = Blog.all
  end

  def edit
    @blog = Blog.find params[:id]
  end

  def update
    blog = Blog.find params[:id]

    if blog.update_attributes blog_params
      redirect_to staff_blogs_path, success: 'Blog was successfully updated'
    else
      render 'edit'
    end
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new blog_params
    @blog.staff = current_user

    if @blog.save
      redirect_to staff_blogs_path, success: 'Blog was successfully created'
    else
      render 'new'
    end
  end

  def destroy
    if Blog.find(params[:id]).destroy
      redirect_to staff_blogs_path, success: 'Blog was successfully deleted'
    end
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :summary, :content, :image, :published, :meta_description)
  end
end

app/controllers/staff/clips_controller.rb
class Staff::ClipsController < Staff::StaffApplicationController
  def index
    @clips = Clip.all
  end

  def show
    @clip = Clip.find(params[:id])
  end

  def edit
    @clip = Clip.find(params[:id])
  end

  def update
    clip = Clip.find(params[:id])

    if clip.update_attributes clip_params
      redirect_to staff_clips_path, success: 'Clip was successfully updated'
    end
  end

  def destroy
    if Clip.find(params[:id]).destroy
      redirect_to staff_clips_path, success: 'Clip was successfully deleted'
    end
  end

  private

  def clip_params
    params.require(:clips).permit(:status)
  end
end

app/controllers/staff/companies_controller.rb
class Staff::CompaniesController < Staff::StaffApplicationController
  layout :resolve_layout

  def index
    @companies = Company.all
  end

  def maps
    @companies = Company.all
    @companies = @companies.joins(:services).where(services: {id: params[:service]}) if params[:service]
    if params[:service_field]
      @companies = @companies.joins(:services).joins('JOIN service_fields ON services.service_field_id = service_fields.id').where(service_fields: {id: params[:service_field]})
    end
    @service_fields = ServiceField.all

    @company_cords = @companies.select(:latitude, :longitude).map do |c|
      {latitude: c.latitude, longitude: c.longitude} if c.latitude && c.longitude
    end.compact.to_json

    respond_to do |format|
      format.html
      format.json { render json: @company_cords}
    end
  end

  def show
    @company = Company.find params[:id]
    @service_fields = ServiceField.all
  end

  def edit
    session[:return_to] ||= request.referer
    @company = Company.find params[:id]
    @service_fields = ServiceField.all
  end

  def update
    @company = Company.find params[:id]

    if @company.update_attributes company_params
      redirect_to session.delete(:return_to), success: 'Company was successfully updated'
    else
      @service_fields = ServiceField.all
      render 'edit'
    end
  end

  def new
    @company = Company.new company_params
    @service_fields = ServiceField.all
  end

  def create
    @company = Company.new company_params
    # Generate a new password for the company.
    password = Digest::SHA2.hexdigest(rand(1000000).to_s)[0..8]
    @company.password = @company.password_confirmation = password

    if @company.save
      # Archive the lead, converted from.
      @company.lead.update_attributes(archived: true) if @company.lead.present?

      # Send welcome mail to company, with login information.
      CompanyMailer.delay(priority: 10).welcome_company(@company, password)

      redirect_to staff_companies_path, success: 'Company was successfully created'
    else
      @service_fields = ServiceField.all
      render 'new'
    end
  end

  def destroy
    if Company.find(params[:id]).update_attributes(active: false)
      redirect_to staff_companies_path, success: 'Company was successfully deleted'
    end
  end

  private

  def company_params
    return if params[:company].nil?
    params.require(:company).permit(:name, :email, :phone, :homepage, :address, :cvr, :company_email, :company_name, :description, :password, :password_confirmation, :lead_id, service_field_ids: [])
  end

  def resolve_layout
    case action_name
      when 'show', 'edit'
        'nested/company'
      else
        'staff_application'
    end
  end
end

app/controllers/staff/customers_controller.rb
class Staff::CustomersController < Staff::StaffApplicationController
  def index
    @customers = Customer.all.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])

    if @customer.update_attributes(customer_params)
      redirect_to staff_customer_path(params[:id]), success: 'Customer was updated'
    else
      render 'edit'
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :phone, :password, :password_confirmation)
  end
end

app/controllers/staff/emails_controller.rb
class Staff::EmailsController < Staff::StaffApplicationController

  def index
    @emails = Email.all
  end

  def edit
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, tables: true, autolink: true, space_after_headers: true, hard_wrap: true)
    @email = Email.find params[:id]
  end

  def update
    email = Email.find params[:id]

    if email.update_attributes(email_params)
      redirect_to staff_emails_path, success: 'Email was updated'
    end
  end

  def show
    @email = Email.find params[:id]
  end

  private

  def email_params
    params.require(:email).permit(:subject, :title, :content)
  end
end

app/controllers/staff/invoices_controller.rb
class Staff::InvoicesController < Staff::StaffApplicationController
  before_filter :if_nested

  # If shown within a company, load and use nested layout.
  def if_nested
    if params[:company_id].present?
      @company = Company.find(params[:company_id])
      self.class.layout 'nested/company'
    end
  end

  def index
    @prev_invoices = @company.invoices.where.not(state: 'open')
  end

end

app/views/staff/companies/_form.html.erb
<% if @company.errors.count > 0 %>
  <div class="ui error message">
    <div class="header">
      There was some problems
    </div>
    <ul class="list">
      <% @company.errors.messages.each do |attribute, messages| %>
        <% messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>



<%= form_for [:staff, @company], html: {class: 'ui form segment', multipart: true } do |f| %>

  <div class="ui segment">
    <h2>Personal / Owner</h2>

    <%= f.hidden_field :lead_id %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label :phone %>
      <%= f.text_field :phone %>
    </div>

    <div class="field">
      <%= f.label :homepage %>
      <%= f.text_field :homepage %>
    </div>

    <% unless @company.new_record? %>
      <div class="two fields">
        <div class="field">
          <%= f.label :password %>
          <%= f.password_field :password %>
        </div>
        <div class="field">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="ui segment">
    <h2>Company</h2>

    <div class="field">
      <%= f.label :company_name %>
      <%= f.text_field :company_name %>
    </div>

    <div class="field">
      <%= f.label :company_email %>
      <%= f.text_field :company_email %>
    </div>

    <div class="field">
      <%= f.label :cvr %>
      <%= f.text_field :cvr %>
    </div>

    <div class="field">
      <%= f.label :address %>
      <%= f.text_field :address %>
    </div>

    <h2>Supported services</h2>
    <% @service_fields.each do |service_field| %>
      <p><%= service_field.name %></p>

      <div class="field">
        <div class="ui checkbox">
          <%= params[:service_field] %>
          <% enabled = @company.service_fields.include?(service_field) %>
          <%= check_box_tag 'company[service_field_ids][]', service_field.id, enabled, id: "service_field_ids_#{service_field.id}" %>
          <%= f.label service_field.name, for: "service_field_ids_#{service_field.id}" %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.submit 'Save', class: 'ui green submit button' %>
    <%= link_to 'Cancel', session[:return_to], class: 'ui blue submit button' %>
  </div>
<% end %>

app/views/staff/companies/edit.html.erb
<div class="content header">
  <h2>Editing <%= @company.company_name %> </h2>
</div>
<%= render 'form' %>

app/views/staff/companies/index.html.erb
<% content_for :statistics do %>
  <h4 class="stat"><em>Total companies: <span><%= @companies.count %></span></em></h4>
<% end %>
<div class="content header">
  <%= link_to '<i class="add icon"></i> Register Company'.html_safe, new_staff_company_path, class: 'ui small green labeled icon button pull-right' %>
	<h2>Companies</h2>
</div>
<table class="ui table segment">
  <thead>
    <tr>
      <th>Id</th>
      <th>Company name</th>
      <th>Owner name</th>
      <th>Email</th>
      <th>Active</th>
      <th>Register date</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @companies.each do |company| %>
    <tr>
      <td><%= company.id %></td>
      <td><%= company.company_name %></td>
      <td><%= company.name %></td>
      <td><%= company.email %></td>
      <td class="<%= company.active ? 'positive' : 'negative' %>"><%= company.active ? 'Yes' : 'No' %></td>
      <td><%= company.created_at %></td>
      <td>
        <%= link_to '<i class="trash icon"></i> X'.html_safe, staff_company_path(company), class: 'ui icon button tiny labeled red pull-right', confirm: 'Are you sure?', method: :delete  %>
        <%= link_to '<i class="edit icon"></i> Edit'.html_safe, edit_staff_company_path(company), class: 'ui icon button tiny labeled blue pull-right'%>
        <%= link_to '<i class="unhide icon"></i> Details'.html_safe, staff_company_path(company), class: 'ui icon button tiny labeled green pull-right', style: 'margin-top: 5px; width: 197px'%>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/staff/companies/maps.html.erb
<% content_for :statistics do %>
  <h4 class="stat"><em>Total companies: <span><%= @companies.count %></span></em></h4>
<% end %>

<% content_for :scripts do %>
  <script>
    $(document).ready(function() {
      var companyCords, service, mode, distance, filter = "";
      companyCords = <%= @company_cords.html_safe %>;
      // Init initial markers.
      L.updateMap(companyCords, 'radius', 10000);

      // On company update map.
      $('#update-map').click(function (e) {
        e.preventDefault();

        service = $('#service').val();
        if(/service-/.test(service)) {
          // Pick id of service-x
          service = service.substr(8);
          filter = '?service=' + service
        }else if(service.length > 0) {
          filter = '?service_field=' + service
        }

        mode = $('#mode').val();
        distance = $('#distance').val();
        if(distance.length == 0) {
          distance = 10000
        }

        $.ajax({
          type: 'GET',
          url: '/maps/companies.json' + filter,
          success: function(cords) {
            L.updateMap(cords, mode, distance);
          }
        });
      });
    });
  </script>
<% end %>

<div class="content header">
  <h2>Company map</h2>
</div>

<div class="ui segment blue">
  <h2>Map settings</h2>

  <%= form_tag staff_company_map_path, method: 'GET', class: 'ui form' do  %>
    <div class="three fields">
      <div class="field input">
        <div class="ui fluid selection dropdown">
          <%= hidden_field_tag :service %>
          <div class="text">Service(field)</div>
          <i class="dropdown icon"></i>
          <div class="menu" style="z-index: 1001;">
            <% @service_fields.each do |sf| %>
              <div class="item" data-value="<%= sf.id %>"><%= sf.name %></div>
              <% sf.services.each do |s| %>
                <div class="item" data-value="service-<%= s.id %>">- <%= s.name %></div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="field input">
        <div class="ui fluid selection dropdown">
          <%= hidden_field_tag :mode %>
          <div class="text">Kort visning</div>
          <i class="dropdown icon"></i>
          <div class="menu" style="z-index: 1001;">
              <div class="item" data-value="radius">Radius</div>
            <div class="item" data-value="pins">Pins</div>
          </div>
        </div>
      </div>
      <div class="field input">
        <%= text_field_tag :form, params[:form], placeholder: 'Circle radius (meter)', id: 'distance' %>
      </div>
    </div>
    <%= submit_tag 'Update map', class: 'ui small green submit button', id: 'update-map' %>
  <% end %>
</div>


<div class="ui table segment">
  <div id="map" style="height: 800px; width: 100%"></div>
</div>

app/views/staff/companies/new.html.erb
<div class="content header">
  <h2>Register new company</h2>
</div>
<%= render 'form' %>

app/views/staff/companies/show.html.erb
<div class="ui segment">
  <div class="content header">
    <h2>Personal / Owner</h2>
	</div>
  <h5 class="ui dividing header">Owner name</h5>
  <p><%= @company.name %></p>
  <h5 class="ui dividing header">Email</h5>
  <p><%= @company.email %></p>
  <h5 class="ui dividing header">Phone</h5>
  <p><%= @company.phone %></p>
  <h5 class="ui dividing header">Homepage</h5>
  <p><%= @company.homepage %></p>
</div>

<div class="ui segment">
  <div class="content header">
    <h2>Company</h2>
	</div>
  <h5 class="ui dividing header">Name</h5>
  <p><%= @company.company_name %></p>
  <h5 class="ui dividing header">Email</h5>
  <p><%= @company.company_email.present? ? @company.company_email : @company.email %></p>
  <h5 class="ui dividing header">CVR</h5>
  <p><%= @company.cvr %></p>
  <h5 class="ui dividing header">Address</h5>
  <p><%= @company.address %></p>

  <h5 class="ui dividing header">Supported services</h5>
  <% @service_fields.each do |service_field| %>
    <% if @company.services.collect(&:service_field).include? service_field %>
      <p><%= service_field.name %></p>
      <% service_field.services.each do |service| %>
        <small><%= service.name if @company.services.include?(service)%></small><br>
      <% end %>
    <% end %>
  <% end %>
</div>