config/routes.rb
Sanatid::Application.routes.draw do
  class FormatTest
    attr_accessor :mime_type

    def initialize(format)
      @mime_type = Mime::Type.lookup_by_extension(format)
    end

    def matches?(request)
      request.format = :html unless request.format == Mime::Type.lookup_by_extension(:json)
      request.format == mime_type
    end
  end

  get 'robots.:format', to: 'application#robots'

  constraints subdomain: ['staff', 'devstaff'] do
    scope module: 'staff', as: 'staff' do
      root to: 'staff_application#index'

      get 'login', to: 'sessions#new', as: 'login'
      get 'logout', to: 'sessions#destroy', as: 'logout'

      resources :sessions
      resources :companies do
        resources :product_subscriptions
        resources :invoices
        get 'cancel_subscription/:id', to: 'product_subscriptions#cancel_subscription', as: 'cancel_subscription'
      end
      get 'maps/companies', to: 'companies#maps', as: 'company_map'
      resources :customers
      resources :staffs
      resources :service_fields
      resources :services
      resources :blogs
      resources :pages
      resources :staffs
      resources :submissions
      resources :newsletter_subscribers
      resources :products
      resources :emails
      resources :product_subscriptions
      resources :clips
      resources :product_families
      resources :coupons
      get 'my_leads', to: 'leads#my_leads'
      get 'leads/signups', to: 'leads#signups', as: 'leads_signups'
      post 'leads/:id/send_presentation', to: 'leads#send_presentation', as: 'lead_send_presentation'
      post 'leads/assign', to: 'leads#assign_leads', as: 'assign_leads'
      resources :leads
      resources :lead_events
      resources :reminders
      resources :uploads
    end
  end

  get 'terms/company', to: 'api/payments#terms_company'
  get 'product_subscriptions/invoice/:id', to: 'api/product_subscriptions#invoice'
  get 'sitemap.xml', to: 'api/sitemaps#index', as: 'sitemap', defaults: { format: :xml }
  get '*path', :to => 'application#index', :constraints => FormatTest.new(:html)
  get '/', :to => 'application#index', :constraints => FormatTest.new(:html)

  namespace :api do
    resources :service_fields, defaults: { format: 'json' }
    resources :services, defaults: { format: 'json' }
    resources :customers, defaults: { format: 'json' }
    resources :companies, defaults: { format: 'json' }
    get '/frontpage_promotions/:id', to: 'companies#frontpage_promotions'
    get '/flow_promotions', to: 'companies#flow_promotion'
    resources :vouchers, defaults: { format: 'json' }
    resources :clips, defaults: { format: 'json' }
    resources :newsletter_subscribers, defaults: { format: 'json' }
    resources :blogs, defaults: { format: 'json' }
    resources :pages, defaults: { format: 'json' }
    resources :staffs, defaults: { format: 'json' }
    resources :submissions, defaults: { format: 'json' }
    resources :products, defaults: { format: 'json' }
    resources :product_families, defaults: { format: 'json' }
    resources :product_subscriptions, defaults: { format: 'json' }
    resources :messages, defaults: { format: 'json' }
    resources :reviews, defaults: { format: 'json' }
    resources :commission_lines, defaults: { format: 'json' }
    resources :menu_items, defaults: { format: 'json' }
    resources :facility_images, defaults: { format: 'json' }
    resources :bookings, defaults: { format: 'json' }

    resources :payments, defaults: { format: 'json' }
    match '/payment' => 'payments#dispatch_handler', via: 'post'
    match '/payment/list_invoices/:id' => 'payments#list_invoices', via: 'get'

    # Product Subscription.
    post '/product_subscriptions/change_subscription_product/:id', to: 'product_subscriptions#change_subscription_product'
    post '/product_subscriptions/cancel_subscription/:id', to: 'product_subscriptions#cancel_subscription'
    post '/product_subscriptions/signup_subscription/:id', to: 'product_subscriptions#signup_subscription'
    post '/product_subscriptions/reactivate_subscription/:id', to: 'product_subscriptions#reactivate_subscription'

    post '/demo/init', to: 'demo#init_demo'

    resources :sessions, except: [:new, :edit, :destroy]
    post 'session' => 'sessions#create', defaults: { format: :json }
    post 'session/reset' => 'sessions#reset', defaults: { format: :json }
  end
end

app/controllers/api/staffs_controller.rb
class Api::StaffsController < ApplicationController
  respond_to :json

  def index
    respond_with Staff.active.published.order(:created_at).load
  end
end

app/controllers/staff/blogs_controller.rb
class Staff::BlogsController < Staff::StaffApplicationController
  def index
    @blogs = Blog.all
  end

  def edit
    @blog = Blog.find params[:id]
  end

  def update
    blog = Blog.find params[:id]

    if blog.update_attributes blog_params
      redirect_to staff_blogs_path, success: 'Blog was successfully updated'
    else
      render 'edit'
    end
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new blog_params
    @blog.staff = current_user

    if @blog.save
      redirect_to staff_blogs_path, success: 'Blog was successfully created'
    else
      render 'new'
    end
  end

  def destroy
    if Blog.find(params[:id]).destroy
      redirect_to staff_blogs_path, success: 'Blog was successfully deleted'
    end
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :summary, :content, :image, :published, :meta_description)
  end
end

app/controllers/staff/clips_controller.rb
class Staff::ClipsController < Staff::StaffApplicationController
  def index
    @clips = Clip.all
  end

  def show
    @clip = Clip.find(params[:id])
  end

  def edit
    @clip = Clip.find(params[:id])
  end

  def update
    clip = Clip.find(params[:id])

    if clip.update_attributes clip_params
      redirect_to staff_clips_path, success: 'Clip was successfully updated'
    end
  end

  def destroy
    if Clip.find(params[:id]).destroy
      redirect_to staff_clips_path, success: 'Clip was successfully deleted'
    end
  end

  private

  def clip_params
    params.require(:clips).permit(:status)
  end
end

app/controllers/staff/companies_controller.rb
class Staff::CompaniesController < Staff::StaffApplicationController
  layout :resolve_layout

  def index
    @companies = Company.all
  end

  def maps
    @companies = Company.all
    @companies = @companies.joins(:services).where(services: {id: params[:service]}) if params[:service]
    if params[:service_field]
      @companies = @companies.joins(:services).joins('JOIN service_fields ON services.service_field_id = service_fields.id').where(service_fields: {id: params[:service_field]})
    end
    @service_fields = ServiceField.all

    @company_cords = @companies.select(:latitude, :longitude).map do |c|
      {latitude: c.latitude, longitude: c.longitude} if c.latitude && c.longitude
    end.compact.to_json

    respond_to do |format|
      format.html
      format.json { render json: @company_cords}
    end
  end

  def show
    @company = Company.find params[:id]
    @service_fields = ServiceField.all
  end

  def edit
    session[:return_to] ||= request.referer
    @company = Company.find params[:id]
    @service_fields = ServiceField.all
  end

  def update
    @company = Company.find params[:id]

    if @company.update_attributes company_params
      redirect_to session.delete(:return_to), success: 'Company was successfully updated'
    else
      @service_fields = ServiceField.all
      render 'edit'
    end
  end

  def new
    @company = Company.new company_params
    @service_fields = ServiceField.all
  end

  def create
    @company = Company.new company_params
    # Generate a new password for the company.
    password = Digest::SHA2.hexdigest(rand(1000000).to_s)[0..8]
    @company.password = @company.password_confirmation = password

    if @company.save
      # Archive the lead, converted from.
      @company.lead.update_attributes(archived: true) if @company.lead.present?

      # Send welcome mail to company, with login information.
      CompanyMailer.delay(priority: 10).welcome_company(@company, password)

      redirect_to staff_companies_path, success: 'Company was successfully created'
    else
      @service_fields = ServiceField.all
      render 'new'
    end
  end

  def destroy
    if Company.find(params[:id]).update_attributes(active: false)
      redirect_to staff_companies_path, success: 'Company was successfully deleted'
    end
  end

  private

  def company_params
    return if params[:company].nil?
    params.require(:company).permit(:name, :email, :phone, :homepage, :address, :cvr, :company_email, :company_name, :description, :password, :password_confirmation, :lead_id, service_field_ids: [])
  end

  def resolve_layout
    case action_name
      when 'show', 'edit'
        'nested/company'
      else
        'staff_application'
    end
  end
end

app/controllers/staff/customers_controller.rb
class Staff::CustomersController < Staff::StaffApplicationController
  def index
    @customers = Customer.all.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])

    if @customer.update_attributes(customer_params)
      redirect_to staff_customer_path(params[:id]), success: 'Customer was updated'
    else
      render 'edit'
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :phone, :password, :password_confirmation)
  end
end

app/controllers/staff/emails_controller.rb
class Staff::EmailsController < Staff::StaffApplicationController

  def index
    @emails = Email.all
  end

  def edit
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, tables: true, autolink: true, space_after_headers: true, hard_wrap: true)
    @email = Email.find params[:id]
  end

  def update
    email = Email.find params[:id]

    if email.update_attributes(email_params)
      redirect_to staff_emails_path, success: 'Email was updated'
    end
  end

  def show
    @email = Email.find params[:id]
  end

  private

  def email_params
    params.require(:email).permit(:subject, :title, :content)
  end
end

app/controllers/staff/invoices_controller.rb
class Staff::InvoicesController < Staff::StaffApplicationController
  before_filter :if_nested

  # If shown within a company, load and use nested layout.
  def if_nested
    if params[:company_id].present?
      @company = Company.find(params[:company_id])
      self.class.layout 'nested/company'
    end
  end

  def index
    @prev_invoices = @company.invoices.where.not(state: 'open')
  end

end

app/controllers/staff/lead_events_controller.rb
class Staff::LeadEventsController < Staff::StaffApplicationController
  def create
    lead_event = LeadEvent.new lead_event_params
    lead_event.staff = current_user

    if lead_event.save
      redirect_to session.delete(:return_to), success: 'Lead event was successfully created'
    end
  end

  private

  def lead_event_params
    params.require(:lead_event).permit(:staff_id, :lead_id, :comment, :event_type, :reason)
  end
end

app/controllers/staff/leads_controller.rb
class Staff::LeadsController < Staff::StaffApplicationController
  def index
    @service_fields = ServiceField.all.select(:name, :id)
    @zips = ['All'] + Lead.select(:city).group(:city).order('city').map(&:city)
    @regions = ['All'] + Lead.select(:region).group(:region).order('region').map(&:region)
    @categories = ['All'] + Lead.select(:category).order(:category).distinct.map(&:category)
    @staffs = Staff.all

    # Apply filters.
    @leads = Lead.active.unassigned.not_converted.filtered(params[:service_field], params[:zip], params[:region], params[:contacted].to_i, params[:category]).page(params[:page]).order('company_name')
  end

  def signups
    @leads = Lead.where(category: 'signup').page(params[:page])
  end

  def show
    @lead = Lead.find(params[:id])
    @staffs = Staff.active
    @lead_event = LeadEvent.new
    @reminder = Reminder.new

    @convert_query = {
      name: @lead.name,
      company_name: @lead.company_name,
      service_field_ids: [@lead.service_field.id],
      phone: @lead.phone.delete(' '),
      homepage: @lead.homepage,
      cvr: @lead.cvr,
      address: "#{@lead.address}#{@lead.city}",
      lead_id: @lead.id
    }

    session[:return_to] = request.referer
  end

  def destroy
    if Lead.find(params[:id]).update_attributes(archived: true)
      redirect_to staff_leads_path, success: 'Lead was successfully deleted'
    end
  end

  def new
    @lead = Lead.new
  end

  def create
    @lead = Lead.new lead_params
    @lead.category = 'manual'

    if @lead.save
      redirect_to staff_leads_path, success: 'Lead was successfully created'
    else
      render 'new'
    end
  end

  def edit
    @lead = Lead.find(params[:id])
  end

  def update
    @lead = Lead.find(params[:id])

    if @lead.update_attributes(lead_params)
      redirect_to staff_lead_path(params[:id]), success: 'Lead was successfully updated'
    else
      render 'edit'
    end
  end

  def assign_leads
    if params[:staff_id] && params[:ids]
      Lead.where(id: params[:ids]).update_all(staff_id: params[:staff_id])
      return redirect_to request.referer, success: 'Assigned leads'
    end

    redirect_to request.referer, error: 'Could not assign leads'
  end

  def my_leads
    @lead_events = current_user.lead_events.page
    @reminders = current_user.reminders.where(date: 2.day.ago..6.months.from_now).order(:date)
  end

  def send_presentation
    lead = Lead.find(params[:id])

    recipient = params[:recipient] || lead.email

    if recipient && lead
      LeadMailer.delay.sanatid_presentation(lead, current_user, recipient)
      flash[:success] = 'The presentation material was send'

      remind_in = params[:reminder].to_i
      if remind_in > 0
        reminder = Reminder.new notify: true, lead: lead, staff: current_user, date: remind_in.days.from_now
        lead_link = "<a href='#{staff_lead_path(lead)}'>#{lead.company_name}</a>"
        reminder.comment = "I send presentation material to #{lead_link}, #{remind_in} days ago. Time to follow up."

        reminder.save
      end
    else
      flash[:error] = 'Recipient or lead was missing'
    end

    redirect_to staff_lead_path(lead)
  end

  private

  def lead_params
    params.require(:lead).permit(:name, :company_name, :email, :phone, :cvr, :address, :zip, :homepage, :service_field, :staff_id)
  end
end

app/controllers/staff/newsletter_subscribers_controller.rb
class Staff::NewsletterSubscribersController < Staff::StaffApplicationController
  def index
    @subscribers = NewsletterSubscriber.all.order(:created_at)
  end

  def destroy
    if NewsletterSubscriber.find(params[:id]).destroy
      redirect_to staff_newsletter_subscribers_path, success: 'Unsubscribed client'
    end
  end
end

app/controllers/staff/pages_controller.rb
class Staff::PagesController < Staff::StaffApplicationController
  def index
    @pages = Page.order(:weight).where(category: params[:category], parent_id: nil)
    session[:return_to] = request.original_url
  end

  def show
    @page = Page.find params[:id]
  end

  def new
    @parents = Page.where(category: params[:category], parent_id: nil)
    @page = Page.new
  end

  def create
    page = Page.new page_params

    if page.save
      redirect_to session.delete(:return_to), success: 'Page was successfully created'
    end
  end

  def edit
    @parents = Page.where(category: params[:category], parent_id: nil)
    @page = Page.find params[:id]
  end

  def update
    page = Page.find params[:id]

    if page.update_attributes page_params
      redirect_to session.delete(:return_to), success: 'Page was successfully updated'
    else
      render 'edit'
    end
  end

  def destroy
    if Page.find(params[:id]).destroy
      redirect_to session.delete(:return_to), success: 'Page was successfully deleted'
    end
  end

  private

  def page_params
    params.require(:page).permit(:category, :title, :weight, :content, :slug, :published, :parent_id)
  end
end

app/controllers/staff/product_families_controller.rb
class Staff::ProductFamiliesController < Staff::StaffApplicationController
  def new
    @product_family = ProductFamily.new
  end

  def create
    @product_family = ProductFamily.new product_family_params

    if @product_family.save
      redirect_to staff_products_path, success: 'Product family was successfully created'
    else
      render 'new'
    end
  end

  def edit
    @product_family = ProductFamily.find(params[:id])
  end

  def update
    @product_family = ProductFamily.find(params[:id])

    if @product_family.update_attributes(product_family_params)
      redirect_to staff_products_path, success: 'Product family was successfully updated'
    else
      render 'edit'
    end
  end

  def destroy
    if ProductFamily.find(params[:id]).destroy
      redirect_to staff_products_path, success: 'Product family was successfully deleted'
    end
  end

  private

  def product_family_params
    params.require(:product_family).permit(:name, :description)
  end
end

app/controllers/staff/reminders_controller.rb
class Staff::RemindersController < Staff::StaffApplicationController
  def create
    reminder = Reminder.new reminder_params
    reminder.staff = current_user

    if reminder.save
      redirect_to session.delete(:return_to), success: 'Reminder was successfully created'
    end
  end

  def destroy
    if Reminder.find(params[:id]).destroy
      redirect_to staff_my_leads_path, success: 'Reminder was successfully created'
    end
  end

  private

  def reminder_params
    params.require(:reminder).permit(:staff_id, :lead_id, :comment, :date, :notify, :notify_at)
  end
end

app/views/staff/leads/edit.html.erb
<div class="content header">
  <h2>Editing lead for <%= @lead.company_name %> </h2>
</div>
<%= render 'form' %>

app/views/staff/leads/index.html.erb
<% content_for :statistics do %>
  <h4 class="stat"><em>Total leads: <span><%= Lead.count %></span></em></h4>
<% end %>

<% content_for :scripts do %>
  <script>
    $(document).ready(function () {
      $('#mark_all').click(function (e) {
        var checked = $(this).prop('checked') ? true : false;

        $('input[type=checkbox]').prop('checked', checked);
      });
    });
  </script>
<% end %>


<div class="content header">
  <%= link_to '<i class="add icon"></i>Create Lead'.html_safe, new_staff_lead_path, class: 'ui small green labeled icon button pull-right' %>
	<h2>Leads</h2>
</div>

<%= form_tag staff_leads_path, method: 'GET', class: 'ui large form segment' do  %>
  <div class="ui six column grid filter">
	  <div class="column">
			<div class="field">
				<label>Service Field</label>
			  <%= select_tag(:service_field, options_for_select(@service_fields.map {|sf| [sf.name, sf.id] }, params[:service_field]), class: 'ui dropdown')%>
			</div>
	  </div>
	  <div class="column">
			<div class="field">
			  <label>Zip</label>
			  <%= select_tag(:zip, options_for_select(@zips, params[:zip])) %>
			</div>
	  </div>
    <div class="column">
      <div class="field">
        <label>Region</label>
        <%= select_tag(:region, options_for_select(@regions, params[:region])) %>
      </div>
    </div>
    <div class="column">
			<div class="field">
			  <label>Category</label>
        <%= select_tag(:category, options_for_select(@categories, params[:category])) %>
			</div>
	  </div>
    <div class="column">
      <div class="field">
        <label>Show only leads that hasn't been contacted in the past</label>
        <%= select_tag(:contacted, options_for_select([['All', 0], ['1 Month', 1], ['3 Months', 3], ['6 Months', 6], ['1 Year', 12]], params[:contacted])) %>
      </div>
    </div>
    <div class="column">
			<%= submit_tag :filter, name: nil, class: 'ui blue submit button' %>
	    <%= link_to 'Reset', staff_leads_path, class: 'ui red button' %>
	  </div>
  </div>
<% end %>

<%= form_tag staff_assign_leads_path, method: :post do %>
<div class="ui two column grid filter">
  <div class="column">
    <h3>Assign leads to Staff member.</h3>
    <div class="field">
      <div class="ui selection dropdown">
        <%= hidden_field_tag :staff_id %>
        <div class="text"></div>
        <i class="dropdown icon"></i>
        <div class="menu">
          <div class="item" data-value="">Unassigned</div>
          <% @staffs.each do |s| %>
            <div class="item" data-value="<%= s.id %>"><%= s.name %></div>
          <% end %>
        </div>
      </div>
      <%= button_tag :assign, id: :assign, class: 'ui button green' %>
    </div>
  </div>
  <div class="column">

  </div>
</div>

<table class="ui table segment">
  <thead>
    <tr>
      <th><%= check_box_tag :mark_all, id: :mark_all %></th>
      <th>Company name</th>
      <th>Service Field</th>
      <th>Phone</th>
      <th>Homepage</th>
      <th>Zip</th>
      <th>Region</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @leads.each do |lead| %>
    <tr>
      <td><%= check_box_tag 'ids[]', lead.id %></td>
      <td><%= lead.company_name %></td>
      <td><%= lead.service_field.name %></td>
      <td><%= lead.phone %></td>
      <td><%= link_to lead.homepage, lead.link, target: '_blank' %></td>
      <td><%= lead.city %></td>
      <td><%= lead.region %></td>
      <td>
        <%= link_to '<i class="unhide icon"></i> Details'.html_safe, staff_lead_path(lead), class: 'ui icon button tiny labeled green'  %>
        <%= link_to '<i class="edit icon"></i> Edit'.html_safe, edit_staff_lead_path(lead), class: 'ui icon button tiny labeled blue'%>
        <%= link_to '<i class="trash icon"></i> Delete'.html_safe, staff_lead_path(lead), class: 'ui icon button tiny labeled red', data: { confirm: 'Are you sure?', method: :delete } %>
      </td>
    </tr>
  <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th colspan="3" style="text-align: center;">
        <%= paginate @leads, window: 2 %>
      </th>
      <th colspan="3" style="text-align: center;">
        <%=   %>
      </th>
    </tr>
  </tfoot>
</table>
<% end %>

app/views/staff/leads/new.html.erb
<div class="content header">
  <h2>Creating new lead</h2>
</div>
<%= render 'form' %>

app/views/staff/leads/show.html.erb
<div class="content header">
  <h1>Show lead for <%= @lead.company_name %></h1>
</div>
<div class="ui segment">
  <div class="ui divided list">
    <% @lead.attributes.each do |attr| %>
      <span class="item">
        <div class="ui blue horizontal label"><%= attr[0] %></div>
        <%= attr[1] %>
      </span>
    <% end %>
  </div>

  <%= link_to 'Convert lead to Company', new_staff_company_path(company: @convert_query), class: 'ui green tiny button' %>
  <%= link_to '<i class="edit icon"></i> Edit'.html_safe, edit_staff_lead_path(@lead), class: 'ui icon button tiny labeled blue' %>
</div>

<div class="ui segment">
  <%= form_for [:staff, @lead], html: {class: 'ui form segment' } do |f| %>
    <h3>Assign lead to Staff member.</h3>
    <div class="field">
      <div class="ui selection dropdown">
        <%= f.hidden_field :staff_id %>
        <div class="text"></div>
        <i class="dropdown icon"></i>
        <div class="menu">
          <div class="item" data-value="">Unassigned</div>
          <% @staffs.each do |s| %>
            <div class="item" data-value="<%= s.id %>"><%= s.name %></div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="field">
      <%= f.submit 'Save', class: 'ui green submit button' %>
      <%= link_to 'Cancel', staff_leads_path, class: 'ui blue submit button' %>
    </div>
  <% end %>
</div>

<div class="ui segment">

  <h3>Event log</h3>

  <% @lead.lead_events.each do |event| %>
    <div class="ui label green"><%= event.event_type %></div>
    <% if event.reason %><div class="ui label blue"><%= event.reason %></div> <% end %>
    <p><%= event.comment %></p>
    <em><%= event.created_at %></em>
  <% end %>

  <h4>Send presentation material</h4>
  <%= form_tag staff_lead_send_presentation_path(@lead), class: 'ui form segment' do  %>

    <div class="field">
      <%= label_tag :recipient %>
      <%= text_field_tag :recipient, @lead.email %>
    </div>

    <div class="field">
      <%= label_tag :reminder, 'Remind me in x days (only integers) - insert 0 if you do not wish a reminder' %>
      <%= text_field_tag :reminder, 7, pattern: '^\d{1,2}$' %>
    </div>

    <div class="field">
      <%= submit_tag 'Send material', class: 'ui blue button' %>
    </div>

  <% end %>

  <h4>Create new event</h4>
  <%= form_for [:staff, @lead_event], html: { class: 'ui form segment' } do |f| %>
    <%= f.hidden_field :lead_id, value: @lead.id %>

    <div class="field">
      <%= f.label :event_type %>
      <%= f.select :event_type, ['None', 'Don\'t want to contacted', 'Contacted', 'Denied offer', 'No contact', 'Wrong number', 'Phone busy'] %>
    </div>

    <div class="field lead-reason">
      <%= f.label :reason %>
      <%= f.select :reason, ['Too difficult to use', 'Too expensive', 'No room for extra clients', 'Other'], include_blank: true %>
    </div>

    <div class="field">
      <%= f.label :comment %>
      <%= f.text_area :comment %>
    </div>
    <div class="field">
      <%= f.submit 'Save event', class: 'ui blue button' %>
    </div>
  <% end %>

  <h4>Create new reminder</h4>
  <%= form_for [:staff, @reminder], html: { class: 'ui form segment' } do |f| %>
    <%= f.hidden_field :lead_id, value: @lead.id %>

    <div class="field">
      <%= f.label :date %>
      <%= f.datetime_select :date %>
    </div>

    <div class="field">
      <%= f.label :notify, 'Notify me - by mail' %>
      <%= f.check_box :notify %>
    </div>

    <div class="field">
      <%= f.label :comment %>
      <%= f.text_area :comment %>
    </div>
    <div class="field">
      <%= f.submit 'Create reminder', class: 'ui blue button' %>
    </div>
  <% end %>
</div>

<%= content_for :scripts do %>
  <script>
    $(document).ready(function (){
      $('.lead-reason').hide();
      $('#lead_event_event_type').change(function() {
        if($(this).val() == 'Denied offer') {
          $('.lead-reason').show();
        }else {
          $('#lead_event_reason').val('Select a reason');
          $('.lead-reason').hide();
        }
      });
    });
  </script>
<% end %>

app/views/staff/leads/signups.html.erb
<% content_for :statistics do %>
  <h4 class="stat"><em>Total leads: <span><%= Lead.count %></span></em></h4>
<% end %>

<div class="content header">
	<h2>Signup leads</h2>
</div>

<table class="ui table segment">
  <thead>
    <tr>
      <th>Name</th>
      <th>Company name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @leads.each do |lead| %>
    <tr>
      <td><%= lead.name %></td>
      <td><%= lead.company_name %></td>
      <td><%= lead.phone %></td>
      <td><%= lead.email %></td>
      <td>
        <%= link_to '<i class="unhide icon"></i> Details'.html_safe, staff_lead_path(lead), class: 'ui icon button tiny labeled green'  %>
        <%= link_to '<i class="edit icon"></i> Edit'.html_safe, edit_staff_lead_path(lead), class: 'ui icon button tiny labeled blue'%>
        <%= link_to '<i class="trash icon"></i> Delete'.html_safe, staff_lead_path(lead), class: 'ui icon button tiny labeled red', data: { confirm: 'Are you sure?', method: :delete } %>
      </td>
    </tr>
  <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th colspan="6" style="text-align: center;">
        <%= paginate @leads, window: 2 %>
      </th>
    </tr>
  </tfoot>
</table>