config/routes.rb
Sanatid::Application.routes.draw do
  class FormatTest
    attr_accessor :mime_type

    def initialize(format)
      @mime_type = Mime::Type.lookup_by_extension(format)
    end

    def matches?(request)
      request.format = :html unless request.format == Mime::Type.lookup_by_extension(:json)
      request.format == mime_type
    end
  end

  get 'robots.:format', to: 'application#robots'

  constraints subdomain: ['staff', 'devstaff'] do
    scope module: 'staff', as: 'staff' do
      root to: 'staff_application#index'

      get 'login', to: 'sessions#new', as: 'login'
      get 'logout', to: 'sessions#destroy', as: 'logout'

      resources :sessions
      resources :companies do
        resources :product_subscriptions
        resources :invoices
        get 'cancel_subscription/:id', to: 'product_subscriptions#cancel_subscription', as: 'cancel_subscription'
      end
      get 'maps/companies', to: 'companies#maps', as: 'company_map'
      resources :customers
      resources :staffs
      resources :service_fields
      resources :services
      resources :blogs
      resources :pages
      resources :staffs
      resources :submissions
      resources :newsletter_subscribers
      resources :products
      resources :emails
      resources :product_subscriptions
      resources :clips
      resources :product_families
      resources :coupons
      get 'my_leads', to: 'leads#my_leads'
      get 'leads/signups', to: 'leads#signups', as: 'leads_signups'
      post 'leads/:id/send_presentation', to: 'leads#send_presentation', as: 'lead_send_presentation'
      post 'leads/assign', to: 'leads#assign_leads', as: 'assign_leads'
      resources :leads
      resources :lead_events
      resources :reminders
      resources :uploads
    end
  end

  get 'terms/company', to: 'api/payments#terms_company'
  get 'product_subscriptions/invoice/:id', to: 'api/product_subscriptions#invoice'
  get 'sitemap.xml', to: 'api/sitemaps#index', as: 'sitemap', defaults: { format: :xml }
  get '*path', :to => 'application#index', :constraints => FormatTest.new(:html)
  get '/', :to => 'application#index', :constraints => FormatTest.new(:html)

  namespace :api do
    resources :service_fields, defaults: { format: 'json' }
    resources :services, defaults: { format: 'json' }
    resources :customers, defaults: { format: 'json' }
    resources :companies, defaults: { format: 'json' }
    get '/frontpage_promotions/:id', to: 'companies#frontpage_promotions'
    get '/flow_promotions', to: 'companies#flow_promotion'
    resources :vouchers, defaults: { format: 'json' }
    resources :clips, defaults: { format: 'json' }
    resources :newsletter_subscribers, defaults: { format: 'json' }
    resources :blogs, defaults: { format: 'json' }
    resources :pages, defaults: { format: 'json' }
    resources :staffs, defaults: { format: 'json' }
    resources :submissions, defaults: { format: 'json' }
    resources :products, defaults: { format: 'json' }
    resources :product_families, defaults: { format: 'json' }
    resources :product_subscriptions, defaults: { format: 'json' }
    resources :messages, defaults: { format: 'json' }
    resources :reviews, defaults: { format: 'json' }
    resources :commission_lines, defaults: { format: 'json' }
    resources :menu_items, defaults: { format: 'json' }
    resources :facility_images, defaults: { format: 'json' }
    resources :bookings, defaults: { format: 'json' }

    resources :payments, defaults: { format: 'json' }
    match '/payment' => 'payments#dispatch_handler', via: 'post'
    match '/payment/list_invoices/:id' => 'payments#list_invoices', via: 'get'

    # Product Subscription.
    post '/product_subscriptions/change_subscription_product/:id', to: 'product_subscriptions#change_subscription_product'
    post '/product_subscriptions/cancel_subscription/:id', to: 'product_subscriptions#cancel_subscription'
    post '/product_subscriptions/signup_subscription/:id', to: 'product_subscriptions#signup_subscription'
    post '/product_subscriptions/reactivate_subscription/:id', to: 'product_subscriptions#reactivate_subscription'

    post '/demo/init', to: 'demo#init_demo'

    resources :sessions, except: [:new, :edit, :destroy]
    post 'session' => 'sessions#create', defaults: { format: :json }
    post 'session/reset' => 'sessions#reset', defaults: { format: :json }
  end
end

app/controllers/api/staffs_controller.rb
class Api::StaffsController < ApplicationController
  respond_to :json

  def index
    respond_with Staff.active.published.order(:created_at).load
  end
end

app/controllers/staff/blogs_controller.rb
class Staff::BlogsController < Staff::StaffApplicationController
  def index
    @blogs = Blog.all
  end

  def edit
    @blog = Blog.find params[:id]
  end

  def update
    blog = Blog.find params[:id]

    if blog.update_attributes blog_params
      redirect_to staff_blogs_path, success: 'Blog was successfully updated'
    else
      render 'edit'
    end
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new blog_params
    @blog.staff = current_user

    if @blog.save
      redirect_to staff_blogs_path, success: 'Blog was successfully created'
    else
      render 'new'
    end
  end

  def destroy
    if Blog.find(params[:id]).destroy
      redirect_to staff_blogs_path, success: 'Blog was successfully deleted'
    end
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :summary, :content, :image, :published, :meta_description)
  end
end

app/controllers/staff/clips_controller.rb
class Staff::ClipsController < Staff::StaffApplicationController
  def index
    @clips = Clip.all
  end

  def show
    @clip = Clip.find(params[:id])
  end

  def edit
    @clip = Clip.find(params[:id])
  end

  def update
    clip = Clip.find(params[:id])

    if clip.update_attributes clip_params
      redirect_to staff_clips_path, success: 'Clip was successfully updated'
    end
  end

  def destroy
    if Clip.find(params[:id]).destroy
      redirect_to staff_clips_path, success: 'Clip was successfully deleted'
    end
  end

  private

  def clip_params
    params.require(:clips).permit(:status)
  end
end

app/controllers/staff/companies_controller.rb
class Staff::CompaniesController < Staff::StaffApplicationController
  layout :resolve_layout

  def index
    @companies = Company.all
  end

  def maps
    @companies = Company.all
    @companies = @companies.joins(:services).where(services: {id: params[:service]}) if params[:service]
    if params[:service_field]
      @companies = @companies.joins(:services).joins('JOIN service_fields ON services.service_field_id = service_fields.id').where(service_fields: {id: params[:service_field]})
    end
    @service_fields = ServiceField.all

    @company_cords = @companies.select(:latitude, :longitude).map do |c|
      {latitude: c.latitude, longitude: c.longitude} if c.latitude && c.longitude
    end.compact.to_json

    respond_to do |format|
      format.html
      format.json { render json: @company_cords}
    end
  end

  def show
    @company = Company.find params[:id]
    @service_fields = ServiceField.all
  end

  def edit
    session[:return_to] ||= request.referer
    @company = Company.find params[:id]
    @service_fields = ServiceField.all
  end

  def update
    @company = Company.find params[:id]

    if @company.update_attributes company_params
      redirect_to session.delete(:return_to), success: 'Company was successfully updated'
    else
      @service_fields = ServiceField.all
      render 'edit'
    end
  end

  def new
    @company = Company.new company_params
    @service_fields = ServiceField.all
  end

  def create
    @company = Company.new company_params
    # Generate a new password for the company.
    password = Digest::SHA2.hexdigest(rand(1000000).to_s)[0..8]
    @company.password = @company.password_confirmation = password

    if @company.save
      # Archive the lead, converted from.
      @company.lead.update_attributes(archived: true) if @company.lead.present?

      # Send welcome mail to company, with login information.
      CompanyMailer.delay(priority: 10).welcome_company(@company, password)

      redirect_to staff_companies_path, success: 'Company was successfully created'
    else
      @service_fields = ServiceField.all
      render 'new'
    end
  end

  def destroy
    if Company.find(params[:id]).update_attributes(active: false)
      redirect_to staff_companies_path, success: 'Company was successfully deleted'
    end
  end

  private

  def company_params
    return if params[:company].nil?
    params.require(:company).permit(:name, :email, :phone, :homepage, :address, :cvr, :company_email, :company_name, :description, :password, :password_confirmation, :lead_id, service_field_ids: [])
  end

  def resolve_layout
    case action_name
      when 'show', 'edit'
        'nested/company'
      else
        'staff_application'
    end
  end
end

app/controllers/staff/customers_controller.rb
class Staff::CustomersController < Staff::StaffApplicationController
  def index
    @customers = Customer.all.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])

    if @customer.update_attributes(customer_params)
      redirect_to staff_customer_path(params[:id]), success: 'Customer was updated'
    else
      render 'edit'
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :phone, :password, :password_confirmation)
  end
end

app/controllers/staff/emails_controller.rb
class Staff::EmailsController < Staff::StaffApplicationController

  def index
    @emails = Email.all
  end

  def edit
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, tables: true, autolink: true, space_after_headers: true, hard_wrap: true)
    @email = Email.find params[:id]
  end

  def update
    email = Email.find params[:id]

    if email.update_attributes(email_params)
      redirect_to staff_emails_path, success: 'Email was updated'
    end
  end

  def show
    @email = Email.find params[:id]
  end

  private

  def email_params
    params.require(:email).permit(:subject, :title, :content)
  end
end

app/controllers/staff/invoices_controller.rb
class Staff::InvoicesController < Staff::StaffApplicationController
  before_filter :if_nested

  # If shown within a company, load and use nested layout.
  def if_nested
    if params[:company_id].present?
      @company = Company.find(params[:company_id])
      self.class.layout 'nested/company'
    end
  end

  def index
    @prev_invoices = @company.invoices.where.not(state: 'open')
  end

end

app/controllers/staff/lead_events_controller.rb
class Staff::LeadEventsController < Staff::StaffApplicationController
  def create
    lead_event = LeadEvent.new lead_event_params
    lead_event.staff = current_user

    if lead_event.save
      redirect_to session.delete(:return_to), success: 'Lead event was successfully created'
    end
  end

  private

  def lead_event_params
    params.require(:lead_event).permit(:staff_id, :lead_id, :comment, :event_type, :reason)
  end
end

app/controllers/staff/leads_controller.rb
class Staff::LeadsController < Staff::StaffApplicationController
  def index
    @service_fields = ServiceField.all.select(:name, :id)
    @zips = ['All'] + Lead.select(:city).group(:city).order('city').map(&:city)
    @regions = ['All'] + Lead.select(:region).group(:region).order('region').map(&:region)
    @categories = ['All'] + Lead.select(:category).order(:category).distinct.map(&:category)
    @staffs = Staff.all

    # Apply filters.
    @leads = Lead.active.unassigned.not_converted.filtered(params[:service_field], params[:zip], params[:region], params[:contacted].to_i, params[:category]).page(params[:page]).order('company_name')
  end

  def signups
    @leads = Lead.where(category: 'signup').page(params[:page])
  end

  def show
    @lead = Lead.find(params[:id])
    @staffs = Staff.active
    @lead_event = LeadEvent.new
    @reminder = Reminder.new

    @convert_query = {
      name: @lead.name,
      company_name: @lead.company_name,
      service_field_ids: [@lead.service_field.id],
      phone: @lead.phone.delete(' '),
      homepage: @lead.homepage,
      cvr: @lead.cvr,
      address: "#{@lead.address}#{@lead.city}",
      lead_id: @lead.id
    }

    session[:return_to] = request.referer
  end

  def destroy
    if Lead.find(params[:id]).update_attributes(archived: true)
      redirect_to staff_leads_path, success: 'Lead was successfully deleted'
    end
  end

  def new
    @lead = Lead.new
  end

  def create
    @lead = Lead.new lead_params
    @lead.category = 'manual'

    if @lead.save
      redirect_to staff_leads_path, success: 'Lead was successfully created'
    else
      render 'new'
    end
  end

  def edit
    @lead = Lead.find(params[:id])
  end

  def update
    @lead = Lead.find(params[:id])

    if @lead.update_attributes(lead_params)
      redirect_to staff_lead_path(params[:id]), success: 'Lead was successfully updated'
    else
      render 'edit'
    end
  end

  def assign_leads
    if params[:staff_id] && params[:ids]
      Lead.where(id: params[:ids]).update_all(staff_id: params[:staff_id])
      return redirect_to request.referer, success: 'Assigned leads'
    end

    redirect_to request.referer, error: 'Could not assign leads'
  end

  def my_leads
    @lead_events = current_user.lead_events.page
    @reminders = current_user.reminders.where(date: 2.day.ago..6.months.from_now).order(:date)
  end

  def send_presentation
    lead = Lead.find(params[:id])

    recipient = params[:recipient] || lead.email

    if recipient && lead
      LeadMailer.delay.sanatid_presentation(lead, current_user, recipient)
      flash[:success] = 'The presentation material was send'

      remind_in = params[:reminder].to_i
      if remind_in > 0
        reminder = Reminder.new notify: true, lead: lead, staff: current_user, date: remind_in.days.from_now
        lead_link = "<a href='#{staff_lead_path(lead)}'>#{lead.company_name}</a>"
        reminder.comment = "I send presentation material to #{lead_link}, #{remind_in} days ago. Time to follow up."

        reminder.save
      end
    else
      flash[:error] = 'Recipient or lead was missing'
    end

    redirect_to staff_lead_path(lead)
  end

  private

  def lead_params
    params.require(:lead).permit(:name, :company_name, :email, :phone, :cvr, :address, :zip, :homepage, :service_field, :staff_id)
  end
end

app/controllers/staff/newsletter_subscribers_controller.rb
class Staff::NewsletterSubscribersController < Staff::StaffApplicationController
  def index
    @subscribers = NewsletterSubscriber.all.order(:created_at)
  end

  def destroy
    if NewsletterSubscriber.find(params[:id]).destroy
      redirect_to staff_newsletter_subscribers_path, success: 'Unsubscribed client'
    end
  end
end

app/controllers/staff/pages_controller.rb
class Staff::PagesController < Staff::StaffApplicationController
  def index
    @pages = Page.order(:weight).where(category: params[:category], parent_id: nil)
    session[:return_to] = request.original_url
  end

  def show
    @page = Page.find params[:id]
  end

  def new
    @parents = Page.where(category: params[:category], parent_id: nil)
    @page = Page.new
  end

  def create
    page = Page.new page_params

    if page.save
      redirect_to session.delete(:return_to), success: 'Page was successfully created'
    end
  end

  def edit
    @parents = Page.where(category: params[:category], parent_id: nil)
    @page = Page.find params[:id]
  end

  def update
    page = Page.find params[:id]

    if page.update_attributes page_params
      redirect_to session.delete(:return_to), success: 'Page was successfully updated'
    else
      render 'edit'
    end
  end

  def destroy
    if Page.find(params[:id]).destroy
      redirect_to session.delete(:return_to), success: 'Page was successfully deleted'
    end
  end

  private

  def page_params
    params.require(:page).permit(:category, :title, :weight, :content, :slug, :published, :parent_id)
  end
end

app/controllers/staff/product_families_controller.rb
class Staff::ProductFamiliesController < Staff::StaffApplicationController
  def new
    @product_family = ProductFamily.new
  end

  def create
    @product_family = ProductFamily.new product_family_params

    if @product_family.save
      redirect_to staff_products_path, success: 'Product family was successfully created'
    else
      render 'new'
    end
  end

  def edit
    @product_family = ProductFamily.find(params[:id])
  end

  def update
    @product_family = ProductFamily.find(params[:id])

    if @product_family.update_attributes(product_family_params)
      redirect_to staff_products_path, success: 'Product family was successfully updated'
    else
      render 'edit'
    end
  end

  def destroy
    if ProductFamily.find(params[:id]).destroy
      redirect_to staff_products_path, success: 'Product family was successfully deleted'
    end
  end

  private

  def product_family_params
    params.require(:product_family).permit(:name, :description)
  end
end

app/controllers/staff/reminders_controller.rb
class Staff::RemindersController < Staff::StaffApplicationController
  def create
    reminder = Reminder.new reminder_params
    reminder.staff = current_user

    if reminder.save
      redirect_to session.delete(:return_to), success: 'Reminder was successfully created'
    end
  end

  def destroy
    if Reminder.find(params[:id]).destroy
      redirect_to staff_my_leads_path, success: 'Reminder was successfully created'
    end
  end

  private

  def reminder_params
    params.require(:reminder).permit(:staff_id, :lead_id, :comment, :date, :notify, :notify_at)
  end
end

app/views/staff/staffs/_form.html.erb
<% @staff.errors.messages.each { |e| puts e } if @staff.errors %>

<%= form_for [:staff, @staff], html: {class: 'ui form segment', multipart: true } do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :job_title %>
    <%= f.text_field :job_title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>

    <% if @staff.image? %>
      <p>Avatar:</p> <%= image_tag @staff.image_url(:avatar) %>
      <p>Small avatar:</p> <%= image_tag @staff.image_url(:small_avatar) %>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="two fields">
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
  </div>

  <% if current_user.has_role?('administrator') %>
    <div class="field">
      <%= f.label :staff_role_id, 'Role' %>
      <% selected = @staff.staff_role.present? ? @staff.staff_role.id : 0 %>
      <%= f.select :staff_role_id, @roles.collect { |role| [role.name.humanize, role.id] }, selected: selected %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :twitter %>
    <%= f.text_field :twitter %>
  </div>

  <div class="field">
    <%= f.label :linkedin %>
    <%= f.text_field :linkedin %>
  </div>

  <div class="field">
    <div class="ui checkbox">
      <%= f.check_box :published %>
      <%= f.label :published %>
    </div>
  </div>

  <div class="field">
    <%= f.submit 'Save', class: 'ui green submit button' %>
    <%= link_to 'Cancel', staff_staffs_path, class: 'ui blue submit button' %>
  </div>
<% end %>

app/views/staff/staffs/edit.html.erb
<div class="content header">
  <h2>Editing <%= @staff.name %> </h2>
</div>
<%= render 'form' %>

app/views/staff/staffs/index.html.erb
<% content_for :statistics do %>
  <h4 class="stat"><em>Total Staff Members: <span><%= @staffs.count %></span></em></h4>
<% end %>
<div class="content header">
  <%= link_to '<i class="add icon"></i> Add staff member'.html_safe, new_staff_staff_path, class: 'ui small green labeled icon button pull-right' %>
	<h2>Staff members</h2>
</div>

<table class="ui table segment">
  <thead>
    <tr>
      <th>Name</th>
      <th>Job title</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Published</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @staffs.each do |staff| %>
    <tr>
      <td><strong><%= staff.name %></strong></td>
      <td><%= staff.job_title %></td>
      <td><%= staff.email %></td>
      <td><%= staff.phone %></td>
      <td class="<%= staff.published ? 'positive' : 'warning' %>"><%= staff.published ? 'Yes' : 'No' %></td>
      <td>
        <%= link_to '<i class="trash icon"></i> X'.html_safe, staff_staff_path(staff), class: 'ui icon button tiny labeled red pull-right', confirm: 'Are you sure?', method: :delete  %>
        <%= link_to '<i class="edit icon"></i> Edit'.html_safe, edit_staff_staff_path(staff), class: 'ui icon button tiny labeled blue pull-right'%>

        <%= link_to '<i class="unhide icon"></i> View details'.html_safe, staff_staff_path(staff), class: 'ui icon button tiny labeled green pull-right', style: 'margin-top: 5px; width: 197px'%>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/staff/staffs/new.html.erb
<div class="content header">
  <h2>Creating new Staff member</h2>
</div>
<%= render 'form' %>

app/views/staff/staffs/show.html.erb
<div class="content header">
  <h1>Details for <%= @staff.name %></h1>
</div>
<% if @staff.image? %>
  <%= image_tag @staff.image_url(:avatar) %>
<% end %>

<div class="ui divided list">
  <span class="item">
    <div class="ui blue horizontal label">Job title</div>
    <%= @staff.job_title %>
  </span>

  <div class="item">
    <div class="ui blue horizontal label">Description</div>
    <%= @staff.description %>
  </div>

  <div class="item">
    <div class="ui blue horizontal label">Email</div>
    <%= @staff.email %>
  </div>

  <div class="item">
    <div class="ui blue horizontal label">phone</div>
    <%= @staff.phone %>
  </div>

  <div class="item">
    <div class="ui blue horizontal label">published</div>
    <%= @staff.published ? 'Yes' : 'No' %>
  </div>

  <div class="item">
    <div class="ui blue horizontal label">twitter</div>
    <%= @staff.twitter %>
  </div>

  <div class="item">
    <div class="ui blue horizontal label">linkedin</div>
    <%= @staff.linkedin %>
  </div>
</div>